In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("preprocess_news_data.csv", encoding = 'latin1')
df.head()

c:\users\abid inamdar\appdata\local\programs\python\python36-32\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,128) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,author,title,timestamp,text,spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,...,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128
0,NaN,Why Bitcoin and Crypto Have No Future Ã¢ÂÂ T...,2018-10-19T03:00:00.000+03:00,Cryptoasset enthusiast and investor. economics...,0,7,1528,519,775,Cryptoasset enthusiast investor. economics. Oc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Deduct tithes straight from workersÃ¢ÂÂ sala...,2018-10-29T02:00:00.000+02:00,Deduct tithes straight from workersÃ¢ÂÂ sala...,0,10,4005,4914,1426,"Deduct tithes straight workersÃ¢ÂÂ salaries,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mark Townsend,Tommy Robinson Ã¢ÂÂstands to make ÃÂ£1mÃ¢Â...,2018-10-27T18:56:00.000+03:00,Tommy Robinson could make more than ÃÂ£1m fro...,0,10,8429,8507,1617,Tommy Robinson could make ÃÂ£1m potential tri...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Kate Rooney,Fidelity launches trade execution and custody ...,2018-10-15T20:30:00.000+03:00,Bitcoin Fidelity just made it easier for hedge...,0,7,1431,299,783,Bitcoin Fidelity made easier hedge funds pros ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,theblaze.com,WATCH: Hillary Clinton jokes about black Democ...,2018-10-30T07:20:00.000+02:00,Hillary Clinton appeared quite amused with her...,0,10,4289,1107,1445,Hillary Clinton appeared quite amused making j...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# df['timestamp'].apply(lambda x:)
# df[df.timestamp =='^2018-10-30']
df["date"] = pd.to_datetime(df.timestamp,errors = 'coerce')
df.head()

,author,title,timestamp,text,spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,date
0,NaN,Why Bitcoin and Crypto Have No Future Ã¢ÂÂ T...,2018-10-19T03:00:00.000+03:00,Cryptoasset enthusiast and investor. economics...,0,7,1528,519,775,Cryptoasset enthusiast investor. economics. Oc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-19 00:00:00
1,NaN,Deduct tithes straight from workersÃ¢ÂÂ sala...,2018-10-29T02:00:00.000+02:00,Deduct tithes straight from workersÃ¢ÂÂ sala...,0,10,4005,4914,1426,"Deduct tithes straight workersÃ¢ÂÂ salaries,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-29 00:00:00
2,Mark Townsend,Tommy Robinson Ã¢ÂÂstands to make ÃÂ£1mÃ¢Â...,2018-10-27T18:56:00.000+03:00,Tommy Robinson could make more than ÃÂ£1m fro...,0,10,8429,8507,1617,Tommy Robinson could make ÃÂ£1m potential tri...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-27 15:56:00
3,Kate Rooney,Fidelity launches trade execution and custody ...,2018-10-15T20:30:00.000+03:00,Bitcoin Fidelity just made it easier for hedge...,0,7,1431,299,783,Bitcoin Fidelity made easier hedge funds pros ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-15 17:30:00
4,theblaze.com,WATCH: Hillary Clinton jokes about black Democ...,2018-10-30T07:20:00.000+02:00,Hillary Clinton appeared quite amused with her...,0,10,4289,1107,1445,Hillary Clinton appeared quite amused making j...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30 05:20:00

In [4]:
df.sort_values(by = 'date',inplace=True)
df.head()

,author,title,timestamp,text,spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,date
40873,"""""Functions and Responsibilities",December 24,2004,http://bit.ly/1OpRm9c .,NaN,NaN,NaN,NaN,NaN,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004-01-01
40868,The News,December 22,2010,http://bit.ly/1huHRXs .,NaN,NaN,NaN,NaN,NaN,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010-01-01
46114,"""""Belarus: Open Joint NGO Letter to the Parli...",October 20,2011,http://bit.ly/1KdT1H4 .,NaN,NaN,NaN,NaN,NaN,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-01-01
40891,The Express Tribune,March 20,2012,http://bit.ly/1QeD0pE .,NaN,NaN,NaN,NaN,NaN,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-01-01
40867,"""""Country Profile Ã¢ÂÂ Pakistan",August 6,2012,http://bit.ly/1LDXNEX .,NaN,NaN,NaN,NaN,NaN,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012-01-01

In [5]:
df.to_csv('csv_for_30.csv',sep=',',encoding='utf-8')

In [17]:
df[df.date =='2018-10-30']

,author,title,timestamp,text,spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,...,Unnamed: 120,Unnamed: 121,Unnamed: 122,Unnamed: 123,Unnamed: 124,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,date
1534,Bloomberg News,Pot entrepreneurs target Asian money at Hong K...,2018-10-30T02:00:00.000+02:00,Seven years. ThatÃ¢ÂÂs how much jail time yo...,0.733,0,0,0,0,Seven years. ThatÃ¢ÂÂs much jail time get sm...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
1527,NaN,Distributed Dialogues: Political Censorship in...,2018-10-30T02:00:00.000+02:00,Distributed Dialogues: Political Censorship in...,0,0,0,0,0,Distributed Dialogues: Political Censorship Ch...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24901,Trevor Kearing,Sojourn (SOJ) Price Tops $0.23 on Exchanges - ...,2018-10-30T02:00:00.000+02:00,Tweet\r\nSojourn (CURRENCY:SOJ) traded flat ag...,0.002,0,0,0,0,Tweet Sojourn (CURRENCY:SOJ) traded flat dolla...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
14464,Bloomberg News,"Happy birthday, bitcoin!: 10 years on, valuati...",2018-10-30T02:00:00.000+02:00,Happy Anniversary to Bitcoin!\r\nIt was Hallow...,0,0,0,0,0,Happy Anniversary Bitcoin! It Halloween 2008 S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24777,Midwest Communications Inc.,Coinbase valued at $8 billion in latest fundra...,2018-10-30T02:00:00.000+02:00,Coinbase valued at $8 billion in latest fundra...,0,0,0,0,0,Coinbase valued $8 billion latest fundraising ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
1562,NaN,Swamp not Drained? US Voters Fear Politicians ...,2018-10-30T02:00:00.000+02:00,"October 30, 2018 22:33 CET Swamp not Drained? ...",0,0,0,0,0,"October 30, 2018 22:33 CET Swamp Drained? 64% ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24837,NaN,"Oyster Protocol Founder Exit Scams, Steals $30...",2018-10-30T02:00:00.000+02:00,"October 30, 2018 21:30 CET Oyster Protocol Fou...",0,0,0,0,0,"October 30, 2018 21:30 CET Oyster Protocol Fou...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
14452,Bloomberg News,"Happy birthday, bitcoin!: 10 years on, valuati...",2018-10-30T02:00:00.000+02:00,Happy Anniversary to Bitcoin!\r\nIt was Hallow...,0,0,0,0,0,Happy Anniversary Bitcoin! It Halloween 2008 S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
11999,NaN,RussiaÃ¢ÂÂs Financial Watchdog to Oversee th...,2018-10-30T02:00:00.000+02:00,RussiaÃ¢ÂÂs Financial Watchdog to Oversee th...,0,0,0,0,0,RussiaÃ¢ÂÂs Financial Watchdog Oversee Crypt...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
11975,warrick,BitcoinÃ¢ÂÂs slump might not be over yet,2018-10-30T02:00:00.000+02:00,It's looks like huge correction on it's way fo...,0,0,0,0,0,"It's looks like huge correction way Bitcoin , ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
1538,NaN,Taking an Identity Selfie Ã¢ÂÂ Self-Sovereig...,2018-10-30T02:00:00.000+02:00,Taking an Identity Selfie Ã¢ÂÂ Self-Sovereig...,0.003,0,0,0,0,Taking Identity Selfie Ã¢ÂÂ Self-Sovereign I...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24891,Tyrone Williams,SiaCashCoin Hits One Day Trading Volume of $12...,2018-10-30T02:00:00.000+02:00,Tweet\r\nSiaCashCoin (CURRENCY:SCC) traded 0.1...,0.007,0,0,0,0,Tweet SiaCashCoin (CURRENCY:SCC) traded 0.1% h...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24815,Aayush Jindal,Ethereum Price Analysis: ETH/USD Sellers In Co...,2018-10-30T02:00:00.000+02:00,Ethereum Price Analysis: ETH/USD Sellers In Co...,0.078,0,0,0,0,Ethereum Price Analysis: ETH/USD Sellers In Co...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
11971,NaN,Ethereum Classic Price Analysis: ETC/USD Selle...,2018-10-30T02:00:00.000+02:00,Key Highlights Ethereum classic price declined...,0,0,0,0,0,Key Highlights Ethereum classic price declined...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24918,NaN,"Daily Byte: Wednesday, October 31, 2018 (Bitco...",2018-10-30T02:00:00.000+02:00,LinkedIn Cancel In this very special bitcoin-h...,0,0,0,0,0,LinkedIn Cancel In special bitcoin-heavy editi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24907,NaN,A Closer Look at a Mining Hub in Kenya with Bi...,2018-10-30T02:00:00.000+02:00,A Closer Look at a Mining Hub in Kenya with Bi...,0,0,0,0,0,A Closer Look Mining Hub Kenya Bithub Africa B...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
12000,NaN,climate change: Bitcoin can push global warmin...,2018-10-30T02:00:00.000+02:00,global warming Bitcoin can push global warming...,0.383,0,0,0,0,global warming Bitcoin push global warming 2 d...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
11996,michaelmiterko,Nearly 10% of all bitcoins havenÃ¢ÂÂt moved ...,2018-10-30T02:00:00.000+02:00,"as an ex bitcoin collector myself, and being i...",0,0,0,0,0,"ex bitcoin collector myself, game since 2011. ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
50772,NaN,"Groups protest, seek justice for rape victim, ...",2018-10-30T02:00:00.000+02:00,Late Elizabeth Ochanya John Charles Makurdi Th...,0.122,0,5,0,3,Late Elizabeth Ochanya John Charles Makurdi Th...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
1587,Tyrone Williams,SproutsExtreme (SPEX) Hits Market Capitalizati...,2018-10-30T02:00:00.000+02:00,Tweet\r\nSproutsExtreme (CURRENCY:SPEX) traded...,0.001,0,0,0,0,Tweet SproutsExtreme (CURRENCY:SPEX) traded fl...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24844,CryptStorm.com,VanEck Deliberates Bitcoin ETF With SEC After ...,2018-10-30T02:00:00.000+02:00,VanEck issued a reply to the U.S. Securities a...,0.002,0,0,0,4,VanEck issued reply U.S. Securities Exchange C...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
24780,MarcusConn,At some point youÃ¢ÂÂll retire. HereÃ¢ÂÂs ...,2018-10-30T02:00:00.000+02:00,"This statement is invalid, ""putting everything...",0,0,0,0,0,"This statement invalid, ""putting everything te...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
17467,NaN,Security agents Ã¢ÂÂll henceforth arrest hat...,2018-10-30T02:00:00.000+02:00,President Muhammadu Buhari JOHN ALECHENU and L...,0,0,0,0,0,President Muhammadu Buhari JOHN ALECHENU LEKE ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
27368,Sarah Jenn,EOS Price Watch: Sharp Triangle Breakout | New...,2018-10-30T02:00:00.000+02:00,EOS Price Watch: Sharp Triangle Breakout Sarah...,0.257,0,0,0,0,EOS Price Watch: Sharp Triangle Breakout Sarah...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
9420,NaN,BitcoinÃ¢ÂÂs slump might not be over yet,2018-10-30T02:00:00.000+02:00,Bitcoin bulls could be in for more bad news. L...,0,0,0,0,4,Bitcoin bulls could bad news. Long-term techni...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
9422,ZUU,Ã¢ÂÂInvesting 10% of Assets in Bitcoin and E...,2018-10-30T02:00:00.000+02:00,Ã¢ÂÂInvesting 10% of Assets in Bitcoin and E...,0.001,0,0,0,0,Ã¢ÂÂInvesting 10% Assets Bitcoin EthereumÃ¢Â...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
27353,Crypto Daily,Cryptocurrency & Bitcoin News App Review - Cry...,2018-10-30T02:00:00.000+02:00,No Comments / 3174 views\r\nCryptocurrency & B...,0,0,0,0,0,No Comments / 3174 views Cryptocurrency & Bitc...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
9398,Latisha Jones,Neurotoken Market Cap Reaches $3.62 Million (N...,2018-10-30T02:00:00.000+02:00,Tweet\r\nNeurotoken (CURRENCY:NTK) traded 10.8...,0.022,0,0,0,0,Tweet Neurotoken (CURRENCY:NTK) traded 10.8% l...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
9419,NaN,Bitcoin can push global warming above 2 degree...,2018-10-30T02:00:00.000+02:00,Bitcoin can push global warming above 2 degree...,0.083,0,10,0,2,Bitcoin push global warming 2 degrees Celsius ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
9396,NaN,JPMorgan Is Using Ethereum-Based Blockchain to...,2018-10-30T02:00:00.000+02:00,View All Result JPMorgan Is Using Ethereum-Bas...,0.001,0,0,0,0,View All Result JPMorgan Is Using Ethereum-Bas...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6751,Yulia Mosaleva,Happy birthday Bitcoin! The controversial cryp...,2018-10-30T02:00:00.000+02:00,Controversial digital currency Bitcoin is read...,0.001,0,0,0,0,Controversial digital currency Bitcoin ready c...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
32448,Midwest Communications Inc.,Britain says it may ban some cryptoasset consu...,2018-10-30T02:00:00.000+02:00,Britain says it may ban some cryptoasset consu...,0.495,0,0,0,0,Britain says may ban cryptoasset consumer prod...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
32449,Midwest Communications Inc.,Coinbase valued at $8 billion in latest fundra...,2018-10-30T02:00:00.000+02:00,Coinbase valued at $8 billion in latest fundra...,0,0,0,0,0,Coinbase valued $8 billion latest fundraising ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
32451,Lubomir Tassev,RussiaÃ¢ÂÂs Financial Watchdog to Oversee th...,2018-10-30T02:00:00.000+02:00,| RussiaÃ¢ÂÂs Financial Watchdog to Oversee ...,0.001,0,0,0,0,| RussiaÃ¢ÂÂs Financial Watchdog Oversee Cry...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
6749,NaN,Buy real estate in NYC with bitcoin - LUXUO,2018-10-30T02:00:00.000+02:00,Bell & Ross Buy real estate in NYC with bitcoi...,0,0,0,0,0,Bell & Ross Buy real estate NYC bitcoin Niefer...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
40139,George Bondi,Virtacoinplus Trading 3.1% Higher Over Last 7 ...,2018-10-30T02:00:00.000+02:00,"Posted by George Bondi on Oct 30th, 2018 // No...",0,0,0,0,0,"Posted George Bondi Oct 30th, 2018 // No Comme...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
14389,Midwest Communications Inc.,Britain says it may ban some cryptoasset consu...,2018-10-30T02:00:00.000+02:00,Britain says it may ban some cryptoasset consu...,0.495,0,0,0,0,Britain says may ban cryptoasset consumer prod...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
20015,NaN,LiteCoin Technical Price Analysis(Oct.30th) Ã¢...,2018-10-30T02:00:00.000+02:00,"CryptoCurrency , Litecoin , Price , Trading Li...",0.749,0,0,0,0,"CryptoCurrency , Litecoin , Price , Trading Li...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
40138,NaN,Bitcoin's `Patient Zero' Says Crypto an Experi...,2018-10-30T02:00:00.000+02:00,+ A\r\n(Oct 30): Bitcoin is an intellectual ex...,0,0,0,0,0,+ A (Oct 30): Bitcoin intellectual experiment ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
32440,NaN,Michael Kors Women's Jet Set Travel Large Smar...,2018-10-30T02:00:00.000+02:00,Michael Kors Women's Jet Set Travel Large Smar...,0.016,0,0,0,0,Michael Kors Women's Jet Set Travel Large Smar...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
29911,Aaron Hankin,Bitcoin steady after worst day in nearly 3 wee...,2018-10-30T02:00:00.000+02:00,A day after suffering its biggest 24-hour decl...,0,0,0,0,0,A day suffering biggest 24-hour decline nearly...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
6768,Midwest Communications Inc.,Coinbase valued at $8 billion in latest fundra...,2018-10-30T02:00:00.000+02:00,Coinbase valued at $8 billion in latest fundra...,0,0,0,0,0,Coinbase valued $8 billion latest fundraising ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
48014,Dollar Destruction,Insights on the Future of Cryptocurrency as 20...,2018-10-30T02:00:00.000+02:00,A password will be e-mailed to you. Home Crypt...,0.862,0,0,0,0,A password e-mailed you. Home Cryptocurrency N...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
40158,John Mccorry,"Happy birthday, bitcoin!: 10 years on, valuati...",2018-10-30T02:00:00.000+02:00,See Full Stock Page ÃÂ»\r\nHappy Anniversary ...,0,0,0,0,0,See Full Stock Page ÃÂ» Happy Anniversary Bit...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
42819,NaN,"Top 5 Crypto : EOS, Ripple, Ethereum Classic, ...",2018-10-30T02:00:00.000+02:00,"Top 5 Crypto : EOS, Ripple, Ethereum Classic, ...",0,0,0,0,0,"Top 5 Crypto : EOS, Ripple, Ethereum Classic, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
45421,Patrick Bannon,Tokenbox (TBX) Market Capitalization Reaches $...,2018-10-30T02:00:00.000+02:00,Tweet\r\nTokenbox (CURRENCY:TBX) traded down 0...,0.034,0,0,0,0,Tweet Tokenbox (CURRENCY:TBX) traded 0.4% doll...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
50728,October,Using cryptocurrency in the Tennessee Valley,2018-10-30T02:00:00.000+02:00,Using cryptocurrency in the Tennessee Valley B...,0,0,0,0,0,Using cryptocurrency Tennessee Valley Bitcoin ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
29900,Connor Blenkinsop,"Choosing the Most Secure Crypto Exchange, Expl...",2018-10-30T02:00:00.000+02:00,1. Why canÃ¢ÂÂt I just trust the exchanges? ...,0,0,0,0,0,1. Why canÃ¢ÂÂt I trust exchanges? Although ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
6769,NaN,BCH and EOS Extend Losses to 5% as Bitcoin Dro...,2018-10-30T02:00:00.000+02:00,BCH and EOS Extend Losses to 5% as Bitcoin Pri...,0,0,0,0,0,BCH EOS Extend Losses 5% Bitcoin Price Drops $...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
29908,www.4-traders.com,ABN AMRO Private Banking: various crypto coin ...,2018-10-30T02:00:00.000+02:00,ABN AMRO Private Banking does not yet recognis...,0,0,0,0,0,ABN AMRO Private Banking yet recognise crypto ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
45420,Jeff Wilder,ZCoin (XZC) Trading Up 4.2% Over Last Week - D...,2018-10-30T02:00:00.000+02:00,Tweet\r\nZCoin (CURRENCY:XZC) traded down 4% a...,0.174,0,0,0,0,Tweet ZCoin (CURRENCY:XZC) traded 4% US dollar...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
32442,NaN,Binance Boss Talks Crypto and Blockchain at Fo...,2018-10-30T02:00:00.000+02:00,Admin Leave a Comment on Binance Boss Talks Cr...,0,0,0,0,0,Admin Leave Comment Binance Boss Talks Crypto ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
40128,Crypto Beaking News,Bitcoin 'Patient Zero' Says BTCÃ¢ÂÂs Current...,2018-10-30T02:00:00.000+02:00,Subscribe to updates Unsubscribe from updates ...,0.005,0,0,0,0,Subscribe updates Unsubscribe updates Bitcoin ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
45402,NaN,"UPDATED: We can only pay N22,500 as minimum wa...",2018-10-30T02:00:00.000+02:00,"UPDATED: We can only pay N22,500 as minimum wa...",0.005,0,0,0,0,"UPDATED: We pay N22,500 minimum wage, govs tel...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
48010,Craig Russo,eToro Lists Binance Coin (BNB) as Its 14th Cry...,2018-10-30T02:00:00.000+02:00,eToro Lists Binance Coin (BNB) as Its 14th Cry...,0.728,0,0,0,0,eToro Lists Binance Coin (BNB) Its 14th Crypto...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
22239,NaN,One Day Left To Allocate SFÃ¢ÂÂs Monthly Budget,2018-10-30T02:00:00.000+02:00,SF ANNOUNCES SF Announces 30.10.2018 - 152 vie...,0.017,0,0,0,0,SF ANNOUNCES SF Announces 30.10.2018 - 152 vie...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
48011,Aayush Jindal,Bitcoin Price Watch: BTC/USD At Risk Of More L...,2018-10-30T02:00:00.000+02:00,Bitcoin Price Watch: BTC/USD At Risk Of More L...,0.078,0,0,0,0,Bitcoin Price Watch: BTC/USD At Risk Of More L...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
50784,ZUU,Effects of China ICO Ban on Central Banks of O...,2018-10-30T02:00:00.000+02:00,Effects of China ICO Ban on Central Banks of O...,0.061,0,0,0,2,Effects China ICO Ban Central Banks Other Coun...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
48013,Robertt Bertton,One of cryptoÃ¢ÂÂs longest-running exchanges...,2018-10-30T02:00:00.000+02:00,One of cryptoÃ¢ÂÂs longest-running exchanges...,0,0,0,0,0,One cryptoÃ¢ÂÂs longest-running exchanges so...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30
40175,timesofindia.indiatimes.com,Bitcoin can push global warming above 2 degree...,2018-10-30T02:00:00.000+02:00,Bitcoin can push global warming above 2 degree...,0,0,30,14,22,Bitcoin push global warming 2 degrees Celsius ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-10-30