In [23]:
import pandas as pd
import numpy as np
import time
import datetime
import calendar

In [24]:
df = pd.read_csv("BTCUSD_2018_1min.csv",index_col=False)
df.describe()

,Sr_no,Unix Timestamp,Open,High,Low,Close,Volume
count,490107.000000,4.901070e+05,490107.000000,490107.000000,490107.000000,490107.000000,490107.000000
mean,245053.000000,4.823329e+11,7738.196771,7741.778537,7734.541034,7738.179708,3.184231
std,141481.848528,7.135990e+11,2334.173728,2336.980611,2331.335312,2334.158940,10.442033
min,0.000000,1.514765e+09,3126.880000,3129.600000,3126.880000,3126.880000,0.000000
25%,122526.500000,1.522116e+09,6408.490000,6409.340000,6407.750000,6408.490000,0.003514
50%,245053.000000,1.529468e+09,7099.070000,7100.090000,7096.600000,7099.070000,0.268116
75%,367579.500000,1.540000e+12,8748.480000,8752.740000,8741.780000,8748.470000,2.423694
max,490106.000000,1.550000e+12,17221.960000,17236.460000,17213.790000,17221.960000,791.239751

In [3]:
df.head()

,Unnamed: 0,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume,UnixTime
0,0,1.550000e+12,31-12-18 23:59,BTCUSD,3686.38,3692.35,3685.70,3692.35,4.107691,1546280940
1,1,1.550000e+12,31-12-18 23:58,BTCUSD,3686.38,3686.38,3686.38,3686.38,0.117334,1546280880
2,2,1.550000e+12,31-12-18 23:57,BTCUSD,3686.38,3686.38,3686.38,3686.38,0.089801,1546280820
3,3,1.550000e+12,31-12-18 23:56,BTCUSD,3685.70,3686.38,3683.98,3686.38,8.244595,1546280760
4,4,1.550000e+12,31-12-18 23:55,BTCUSD,3680.14,3685.70,3680.14,3685.70,3.279082,1546280700

In [25]:
pd.to_datetime(df.Date,errors='raise')
df.dtypes

Sr_no               int64
Unix Timestamp    float64
Date               object
Symbol             object
Open              float64
High              float64
Low               float64
Close             float64
Volume            float64
dtype: object

In [26]:
df['UnixTime'] = df.Date.apply(lambda x :int(calendar.timegm(datetime.datetime.strptime(x,"%d-%m-%y %H:%M").timetuple())) + 86400)
df.head()
# (datetime.datetime.strptime('31-12-18 23:59',"%d-%m-%y %H:%M").timetuple())

,Sr_no,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume,UnixTime
0,0,1.550000e+12,31-12-18 23:59,BTCUSD,3686.38,3692.35,3685.70,3692.35,4.107691,1546387140
1,1,1.550000e+12,31-12-18 23:58,BTCUSD,3686.38,3686.38,3686.38,3686.38,0.117334,1546387080
2,2,1.550000e+12,31-12-18 23:57,BTCUSD,3686.38,3686.38,3686.38,3686.38,0.089801,1546387020
3,3,1.550000e+12,31-12-18 23:56,BTCUSD,3685.70,3686.38,3683.98,3686.38,8.244595,1546386960
4,4,1.550000e+12,31-12-18 23:55,BTCUSD,3680.14,3685.70,3680.14,3685.70,3.279082,1546386900

In [27]:
df.to_csv('BTCUSD_2018_1min.csv',sep=',',encoding='utf-8')

In [21]:
df = pd.read_csv("L_25_oct_4 _Nov.csv")
df.head()

,Unnamed: 0,user,fullname,timestamp,likes,replies,retweets,Label (-2 to 2),text
0,0,WayneVaughan,Wayne Vaughan,30-10-18 23:59,12.0,1.0,3.0,1.0,The @Bcoin team gave me a tour of bPanel last ...
1,1,cryptoquotation,CryptoQuotation,30-10-18 23:57,109.0,1.0,30.0,0.0,#bitcoin pic.twitter.com/gvUOtofTwH
2,2,tokyocityboy2,tokyocityboy,30-10-18 23:57,23.0,1.0,59.0,NaN,プレゼント企画します！\n\nリツイート&フォローでお願いします！\n\n10万リップルを1...
3,3,BlockchainPC,BLOCKCHAIN PRIVATE CLIENT SERVICES,30-10-18 23:56,4.0,1.0,1.0,0.0,Goldman Sachs One Step Closer Trading Bitcoin\...
4,4,CryptoGal_io,CryptoGal Podcast,30-10-18 23:54,2.0,1.0,2.0,0.0,NEW NEW --Que mejor compañia q escuchar a @Ro...

In [33]:
print(df.describe())
df.dropna(axis = 0,inplace=True)
print(df.describe())
df.head()

         Unnamed: 0         likes       replies      retweets  \
count  14292.000000  14291.000000  14291.000000  14291.000000
mean    7145.500000     48.753201      5.470086     15.875166
std     4125.889359    222.474907     20.926346     74.583233
min        0.000000      1.000000      1.000000      1.000000
25%     3572.750000      5.000000      1.000000      1.000000
50%     7145.500000     15.000000      2.000000      3.000000
75%    10718.250000     38.000000      4.000000     10.000000
max    14291.000000  18559.000000   1065.000000   5070.000000

       Label (-2 to 2)      UnixTime
count       676.000000  1.429100e+04
mean         -0.007396  1.534749e+09
std           0.621781  1.018330e+07
min          -2.000000  1.515629e+09
25%           0.000000  1.520803e+09
50%           0.000000  1.540617e+09
75%           0.000000  1.540836e+09
max           2.000000  1.541030e+09
       Unnamed: 0        likes     replies    retweets  Label (-2 to 2)  \
count  676.000000   676.000000  676.000000  676.000000       676.000000
mean   394.985207    44.381657    5.692308   15.291420        -0.007396
std    225.536154   102.606530   14.864424   44.598681         0.621781
min      0.000000     1.000000    1.000000    1.000000        -2.000000
25%    195.750000     5.000000    1.000000    1.000000         0.000000
50%    403.500000    15.000000    2.000000    4.000000         0.000000
75%    590.250000    37.000000    5.000000   10.000000         0.000000
max    780.000000  1402.000000  257.000000  558.000000         2.000000

           UnixTime
count  6.760000e+02
mean   1.540927e+09
std    9.457873e+03
min    1.540911e+09
25%    1.540918e+09
50%    1.540926e+09
75%    1.540935e+09
max    1.540944e+09

,Unnamed: 0,Unnamed: 0.1,user,timestamp,likes,replies,retweets,Label (-2 to 2),text,UnixTime
0,0,0,WayneVaughan,2018-10-30 23:59:00,12.0,1.0,3.0,1.0,The @Bcoin team gave me a tour of bPanel last ...,1.540944e+09
1,1,1,cryptoquotation,2018-10-30 23:57:00,109.0,1.0,30.0,0.0,#bitcoin pic.twitter.com/gvUOtofTwH,1.540944e+09
3,3,3,BlockchainPC,2018-10-30 23:56:00,4.0,1.0,1.0,0.0,Goldman Sachs One Step Closer Trading Bitcoin\...,1.540944e+09
4,4,4,CryptoGal_io,2018-10-30 23:54:00,2.0,1.0,2.0,0.0,NEW NEW --Que mejor compañia q escuchar a @Ro...,1.540944e+09
5,5,5,pjf,2018-10-30 23:54:00,29.0,3.0,15.0,0.0,Sources:\r\n\r\n\r\n\r\n- Bitcoin energy consu...,1.540944e+09

In [34]:
df.dtypes

Unnamed: 0           int64
Unnamed: 0.1        object
user                object
timestamp           object
likes              float64
replies            float64
retweets           float64
Label (-2 to 2)    float64
text                object
UnixTime           float64
dtype: object

In [22]:
df.timestamp =  pd.to_datetime(df.timestamp,errors='raise')

In [36]:
df.head()

,Unnamed: 0,Unnamed: 0.1,user,timestamp,likes,replies,retweets,Label (-2 to 2),text,UnixTime
0,0,0,WayneVaughan,2018-10-30 23:59:00,12.0,1.0,3.0,1.0,The @Bcoin team gave me a tour of bPanel last ...,1.540944e+09
1,1,1,cryptoquotation,2018-10-30 23:57:00,109.0,1.0,30.0,0.0,#bitcoin pic.twitter.com/gvUOtofTwH,1.540944e+09
3,3,3,BlockchainPC,2018-10-30 23:56:00,4.0,1.0,1.0,0.0,Goldman Sachs One Step Closer Trading Bitcoin\...,1.540944e+09
4,4,4,CryptoGal_io,2018-10-30 23:54:00,2.0,1.0,2.0,0.0,NEW NEW --Que mejor compañia q escuchar a @Ro...,1.540944e+09
5,5,5,pjf,2018-10-30 23:54:00,29.0,3.0,15.0,0.0,Sources:\r\n\r\n\r\n\r\n- Bitcoin energy consu...,1.540944e+09

In [37]:
df.dtypes

Unnamed: 0                  int64
Unnamed: 0.1               object
user                       object
timestamp          datetime64[ns]
likes                     float64
replies                   float64
retweets                  float64
Label (-2 to 2)           float64
text                       object
UnixTime                  float64
dtype: object

In [38]:
# (df.timestamp - datetime.datetime(1970, 1, 1)).total_seconds() 
df['UnixTime'] = list(((date1 - datetime.datetime(1970, 1, 1)).total_seconds() for date1 in df.timestamp))
df.head()

,Unnamed: 0,Unnamed: 0.1,user,timestamp,likes,replies,retweets,Label (-2 to 2),text,UnixTime
0,0,0,WayneVaughan,2018-10-30 23:59:00,12.0,1.0,3.0,1.0,The @Bcoin team gave me a tour of bPanel last ...,1.540944e+09
1,1,1,cryptoquotation,2018-10-30 23:57:00,109.0,1.0,30.0,0.0,#bitcoin pic.twitter.com/gvUOtofTwH,1.540944e+09
3,3,3,BlockchainPC,2018-10-30 23:56:00,4.0,1.0,1.0,0.0,Goldman Sachs One Step Closer Trading Bitcoin\...,1.540944e+09
4,4,4,CryptoGal_io,2018-10-30 23:54:00,2.0,1.0,2.0,0.0,NEW NEW --Que mejor compañia q escuchar a @Ro...,1.540944e+09
5,5,5,pjf,2018-10-30 23:54:00,29.0,3.0,15.0,0.0,Sources:\r\n\r\n\r\n\r\n- Bitcoin energy consu...,1.540944e+09

In [39]:
df.drop(columns= ['fullname'],inplace = True)
df.head()

ValueError: labels ['fullname'] not contained in axis

In [30]:
df.to_csv("Unix_30_oct_twitter.csv",sep=',',encoding='utf-8')

In [4]:
df = pd.read_csv('f_30_Oct_labeling.csv')
df.head()

,Sr,author,timestamp,title,text,Label (-2 to 2),spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,stem,lem,cap
0,1,Bloomberg News,10/30/18 0:00,Pot entrepreneurs target Asian money at Hong K...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s how much jail t...,NaN,0.733,0.0,0.0,0.0,0.0,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,seven years. thatÃƒÂ¢Ã‚Â€Ã‚Â™ much jail time g...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,SEVEN YEARS. THATÃƒÂ‚Ã‚Â€Ã‚Â™S MUCH JAIL TIME ...
1,2,NaN,10/30/18 0:00,Distributed Dialogues: Political Censorship in...,Distributed Dialogues: Political Censorship in...,NaN,0.000,0.0,0.0,0.0,0.0,Distributed Dialogues: Political Censorship Ch...,distribut dialogues: polit censorship china 20...,Distributed Dialogues: Political Censorship Ch...,DISTRIBUTED DIALOGUES: POLITICAL CENSORSHIP CH...
2,3,Trevor Kearing,10/30/18 0:00,Sojourn (SOJ) Price Tops $0.23 on Exchanges - ...,Tweet\r\r\nSojourn (CURRENCY:SOJ) traded flat ...,NaN,0.002,0.0,0.0,0.0,0.0,Tweet Sojourn (CURRENCY:SOJ) traded flat dolla...,tweet sojourn (currency:soj) trade flat dollar...,Tweet Sojourn (CURRENCY:SOJ) trade flat dollar...,TWEET SOJOURN (CURRENCY:SOJ) TRADED FLAT DOLLA...
3,4,Bloomberg News,10/30/18 0:00,"Happy birthday, bitcoin!: 10 years on, valuati...",Happy Anniversary to Bitcoin!\r\r\nIt was Hall...,NaN,0.000,0.0,0.0,0.0,0.0,Happy Anniversary Bitcoin! It Halloween 2008 S...,happi anniversari bitcoin! It halloween 2008 s...,Happy Anniversary Bitcoin! It Halloween 2008 S...,HAPPY ANNIVERSARY BITCOIN! IT HALLOWEEN 2008 S...
4,5,Midwest Communications Inc.,10/30/18 0:00,Coinbase valued at $8 billion in latest fundra...,Coinbase valued at $8 billion in latest fundra...,NaN,0.000,0.0,0.0,0.0,0.0,Coinbase valued $8 billion latest fundraising ...,coinbas valu $8 billion latest fundrais round ...,Coinbase value $8 billion latest fundraise rou...,COINBASE VALUED $8 BILLION LATEST FUNDRAISING ...

In [5]:
print(df.describe())
# df.dropna(axis = 0,inplace=True)
# print(df.describe())
df.head()

                Sr  Label (-2 to 2)   spam_score  performance_score  \
count  1772.000000              0.0  1763.000000        1763.000000
mean    886.500000              NaN     0.055634           0.017016
std     511.676656              NaN     0.177066           0.302740
min       1.000000              NaN     0.000000           0.000000
25%     443.750000              NaN     0.000000           0.000000
50%     886.500000              NaN     0.000000           0.000000
75%    1329.250000              NaN     0.003000           0.000000
max    1772.000000              NaN     1.000000          10.000000

       facebook_likes  facebook_comments  facebook_shares
count     1763.000000        1763.000000      1763.000000
mean         8.331821           2.353942         3.000567
std        160.955869          51.497954        41.243766
min          0.000000           0.000000         0.000000
25%          0.000000           0.000000         0.000000
50%          0.000000           0.000000         0.000000
75%          0.000000           0.000000         0.000000
max       4409.000000        1799.000000      1445.000000

,Sr,author,timestamp,title,text,Label (-2 to 2),spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,stem,lem,cap
0,1,Bloomberg News,10/30/18 0:00,Pot entrepreneurs target Asian money at Hong K...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s how much jail t...,NaN,0.733,0.0,0.0,0.0,0.0,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,seven years. thatÃƒÂ¢Ã‚Â€Ã‚Â™ much jail time g...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,SEVEN YEARS. THATÃƒÂ‚Ã‚Â€Ã‚Â™S MUCH JAIL TIME ...
1,2,NaN,10/30/18 0:00,Distributed Dialogues: Political Censorship in...,Distributed Dialogues: Political Censorship in...,NaN,0.000,0.0,0.0,0.0,0.0,Distributed Dialogues: Political Censorship Ch...,distribut dialogues: polit censorship china 20...,Distributed Dialogues: Political Censorship Ch...,DISTRIBUTED DIALOGUES: POLITICAL CENSORSHIP CH...
2,3,Trevor Kearing,10/30/18 0:00,Sojourn (SOJ) Price Tops $0.23 on Exchanges - ...,Tweet\r\r\nSojourn (CURRENCY:SOJ) traded flat ...,NaN,0.002,0.0,0.0,0.0,0.0,Tweet Sojourn (CURRENCY:SOJ) traded flat dolla...,tweet sojourn (currency:soj) trade flat dollar...,Tweet Sojourn (CURRENCY:SOJ) trade flat dollar...,TWEET SOJOURN (CURRENCY:SOJ) TRADED FLAT DOLLA...
3,4,Bloomberg News,10/30/18 0:00,"Happy birthday, bitcoin!: 10 years on, valuati...",Happy Anniversary to Bitcoin!\r\r\nIt was Hall...,NaN,0.000,0.0,0.0,0.0,0.0,Happy Anniversary Bitcoin! It Halloween 2008 S...,happi anniversari bitcoin! It halloween 2008 s...,Happy Anniversary Bitcoin! It Halloween 2008 S...,HAPPY ANNIVERSARY BITCOIN! IT HALLOWEEN 2008 S...
4,5,Midwest Communications Inc.,10/30/18 0:00,Coinbase valued at $8 billion in latest fundra...,Coinbase valued at $8 billion in latest fundra...,NaN,0.000,0.0,0.0,0.0,0.0,Coinbase valued $8 billion latest fundraising ...,coinbas valu $8 billion latest fundrais round ...,Coinbase value $8 billion latest fundraise rou...,COINBASE VALUED $8 BILLION LATEST FUNDRAISING ...

In [6]:
df.dtypes

Sr                     int64
author                object
timestamp             object
title                 object
text                  object
Label (-2 to 2)      float64
spam_score           float64
performance_score    float64
facebook_likes       float64
facebook_comments    float64
facebook_shares      float64
preprocess            object
stem                  object
lem                   object
cap                   object
dtype: object

In [7]:
df.timestamp = pd.to_datetime(df.timestamp,errors='raise')
df.dtypes

Sr                            int64
author                       object
timestamp            datetime64[ns]
title                        object
text                         object
Label (-2 to 2)             float64
spam_score                  float64
performance_score           float64
facebook_likes              float64
facebook_comments           float64
facebook_shares             float64
preprocess                   object
stem                         object
lem                          object
cap                          object
dtype: object

In [8]:
df['UnixTime'] = list(((date1 - datetime.datetime(1970, 1, 1)).total_seconds() for date1 in df.timestamp))
df.head()

,Sr,author,timestamp,title,text,Label (-2 to 2),spam_score,performance_score,facebook_likes,facebook_comments,facebook_shares,preprocess,stem,lem,cap,UnixTime
0,1,Bloomberg News,2018-10-30,Pot entrepreneurs target Asian money at Hong K...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s how much jail t...,NaN,0.733,0.0,0.0,0.0,0.0,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,seven years. thatÃƒÂ¢Ã‚Â€Ã‚Â™ much jail time g...,Seven years. ThatÃƒÂ¢Ã‚Â€Ã‚Â™s much jail time ...,SEVEN YEARS. THATÃƒÂ‚Ã‚Â€Ã‚Â™S MUCH JAIL TIME ...,1.540858e+09
1,2,NaN,2018-10-30,Distributed Dialogues: Political Censorship in...,Distributed Dialogues: Political Censorship in...,NaN,0.000,0.0,0.0,0.0,0.0,Distributed Dialogues: Political Censorship Ch...,distribut dialogues: polit censorship china 20...,Distributed Dialogues: Political Censorship Ch...,DISTRIBUTED DIALOGUES: POLITICAL CENSORSHIP CH...,1.540858e+09
2,3,Trevor Kearing,2018-10-30,Sojourn (SOJ) Price Tops $0.23 on Exchanges - ...,Tweet\r\r\nSojourn (CURRENCY:SOJ) traded flat ...,NaN,0.002,0.0,0.0,0.0,0.0,Tweet Sojourn (CURRENCY:SOJ) traded flat dolla...,tweet sojourn (currency:soj) trade flat dollar...,Tweet Sojourn (CURRENCY:SOJ) trade flat dollar...,TWEET SOJOURN (CURRENCY:SOJ) TRADED FLAT DOLLA...,1.540858e+09
3,4,Bloomberg News,2018-10-30,"Happy birthday, bitcoin!: 10 years on, valuati...",Happy Anniversary to Bitcoin!\r\r\nIt was Hall...,NaN,0.000,0.0,0.0,0.0,0.0,Happy Anniversary Bitcoin! It Halloween 2008 S...,happi anniversari bitcoin! It halloween 2008 s...,Happy Anniversary Bitcoin! It Halloween 2008 S...,HAPPY ANNIVERSARY BITCOIN! IT HALLOWEEN 2008 S...,1.540858e+09
4,5,Midwest Communications Inc.,2018-10-30,Coinbase valued at $8 billion in latest fundra...,Coinbase valued at $8 billion in latest fundra...,NaN,0.000,0.0,0.0,0.0,0.0,Coinbase valued $8 billion latest fundraising ...,coinbas valu $8 billion latest fundrais round ...,Coinbase value $8 billion latest fundraise rou...,COINBASE VALUED $8 BILLION LATEST FUNDRAISING ...,1.540858e+09

In [9]:
df.to_csv("Unix_30_oct_news.csv",sep=',',encoding='utf-8')